### ISSUE TITLE
问问twqq的版本选用问题？

### ISSUE THREAD

**Issue by plutoid** [coldnight/pual_bot#17]
我试了下面两个版本，0.17.0 不能登录，0.2.11报下面的错，版本选择需要注意什么吗？之前有跑起来过，现在似乎有变化。 谢谢！
twqq-0.17.0
twqq-0.2.11
/usr/local/lib/python2.7/dist-packages/twqq-0.2.11-py2.7.egg/twqq/requests.py:309: UserWarning: In next version we will rename twqq.requests.FreindInfoRequest to twqq.requests.FriendListRequest

**Comment by coldnight** [comment]
下面不是报错 是个提醒。0.2.11就可以

发自我的 iPhone

**Comment by plutoid** [comment]
可是这段报错结束后，就不能看到什么了，似乎进程变成后台跑了，但我看了下生成的log，似乎在等待输入验证码，可是这时进程在后台跑没法输入。 然后我改成启动本地端口的web服务接受验证码，但是输入验证码后报错，能看到 http://localhost:9000 和输入验证码，下面 log 如下。而且提交验证码后变成“500: Internal Server Error” 错误。

目前twqq 和 tornado 版本

> > > print twqq.**version**
> > > 0.2.11
> > > print tornado.version
> > > 3.2.2

```
    HTTPRequest(protocol='http', host='localhost:9000', method='POST', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Origin': 'http://localhost:9000', 'Content-Length': '34', 'Accept-Language': 'en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4,zh-TW;q=0.2', 'Accept-Encoding': 'gzip,deflate,sdch', 'Host': 'localhost:9000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.137 Safari/537.36', 'Connection': 'keep-alive', 'Referer': 'http://localhost:9000/', 'Cache-Control': 'max-age=0', 'Content-Type': 'application/x-www-form-urlencoded'})
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1320, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1503, in wrapper
        result = method(self, *args, **kwargs)
      File "/home/tianhua/pual_bot/server.py", line 94, in post
        self.webqq.enter_verify_code(code, self.r, self.uin, self.on_callback)
      File "./webqq.py", line 120, in enter_verify_code
        super(Client, self).enter_verify_code(code, r, uin)
      File "build/bdist.linux-i686/egg/twqq/client.py", line 53, in enter_verify_code
        pwd = self.hub.handle_pwd(r, self.hub.check_code.upper(), uin)
      File "build/bdist.linux-i686/egg/twqq/hub.py", line 160, in handle_pwd
        huin = huin.encode('utf-8')
    AttributeError: 'NoneType' object has no attribute 'encode'
[E 140727 22:36:54 web:1856] 500 POST / (127.0.0.1) 14.24ms
```

**Comment by coldnight** [comment]
如果想使用 Web Service 输入验证码, 需要在配置文件里开启 HTTP_CHECKIMG 选项

**Comment by plutoid** [comment]
不好意思没说清楚，我是想说每次执行完启动脚本就自动退到命令行了， 没有地方输入验证码。

```
tianhua@WaterCountry:~/pual_bot$ ./webqq.py 
/usr/local/lib/python2.7/dist-packages/twqq-0.2.11-py2.7.egg/twqq/requests.py:309: UserWarning: In next version we will rename twqq.requests.FreindInfoRequest to twqq.requests.FriendListRequest
tianhua@WaterCountry:~/pual_bot$ 
```

**Comment by coldnight** [comment]
你把 DEBUG 关了吧, DEBUG 关了就会将进程 fork 到后台.

**Comment by plutoid** [comment]
果然，谢谢！
